CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname VARCHAR(40) NOT NULL,
    content TEXT NOT NULL,
    owner_session_id VARCHAR(80) NOT NULL,
    anonymous_token VARCHAR(80) NOT NULL,
    show_images_in_content BOOLEAN NOT NULL,
    view_count BIGINT DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6)
);

CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    parent_comment_id BIGINT,
    nickname VARCHAR(40) NOT NULL,
    content TEXT NOT NULL,
    owner_session_id VARCHAR(80) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_comments_post FOREIGN KEY (post_id) REFERENCES posts (id),
    CONSTRAINT fk_comments_parent FOREIGN KEY (parent_comment_id) REFERENCES comments (id)
);

CREATE TABLE post_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    source_type VARCHAR(20) NOT NULL,
    url VARCHAR(2048) NOT NULL,
    original_filename VARCHAR(255),
    image_order INTEGER NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_post_images_post FOREIGN KEY (post_id) REFERENCES posts (id)
);

CREATE TABLE post_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    owner_session_id VARCHAR(80) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_post_likes_post FOREIGN KEY (post_id) REFERENCES posts (id),
    CONSTRAINT uk_post_likes_post_owner UNIQUE (post_id, owner_session_id)
);

CREATE TABLE comment_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id BIGINT NOT NULL,
    owner_session_id VARCHAR(80) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_comment_likes_comment FOREIGN KEY (comment_id) REFERENCES comments (id),
    CONSTRAINT uk_comment_likes_comment_owner UNIQUE (comment_id, owner_session_id)
);

CREATE TABLE poll_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    content VARCHAR(80) NOT NULL,
    option_order INTEGER NOT NULL,
    CONSTRAINT fk_poll_options_post FOREIGN KEY (post_id) REFERENCES posts (id)
);

CREATE TABLE poll_votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    poll_option_id BIGINT NOT NULL,
    owner_session_id VARCHAR(80) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_poll_votes_post FOREIGN KEY (post_id) REFERENCES posts (id),
    CONSTRAINT fk_poll_votes_option FOREIGN KEY (poll_option_id) REFERENCES poll_options (id),
    CONSTRAINT uk_poll_votes_post_owner UNIQUE (post_id, owner_session_id)
);

CREATE INDEX idx_posts_created_at ON posts (created_at);
CREATE INDEX idx_posts_owner_session_id ON posts (owner_session_id);
CREATE INDEX idx_comments_post_id ON comments (post_id);
CREATE INDEX idx_comments_parent_comment_id ON comments (parent_comment_id);
CREATE INDEX idx_comments_owner_session_id ON comments (owner_session_id);
CREATE INDEX idx_post_images_post_id ON post_images (post_id);
CREATE INDEX idx_post_likes_post_id ON post_likes (post_id);
CREATE INDEX idx_post_likes_owner_session_id ON post_likes (owner_session_id);
CREATE INDEX idx_comment_likes_comment_id ON comment_likes (comment_id);
CREATE INDEX idx_comment_likes_owner_session_id ON comment_likes (owner_session_id);
CREATE INDEX idx_poll_options_post_id ON poll_options (post_id);
CREATE INDEX idx_poll_votes_post_id ON poll_votes (post_id);
CREATE INDEX idx_poll_votes_option_id ON poll_votes (poll_option_id);
CREATE INDEX idx_poll_votes_owner_session_id ON poll_votes (owner_session_id);
